FROM phpmyadmin/phpmyadmin
ENV MYSQL_USER=raam \
    MYSQL_PASSWORD=test1234 \
    MYSQL_ROOT_PASSWORD=test1234
EXPOSE 80
# command to execute
# docker build -t php .
# sudo docker run -d --link mysql:db -p 8182:80 php:latest
# localhost:8182

